### ISSUE TITLE
고양이 사진이 없음

### ISSUE THREAD

**Issue by saroro1** [NyangBotLab/Nyanyai#1]
There aren't any kitty photos. Plz add any kind of kitty!!!!!!!

**Comment by vientorepublic** [comment]
![KakaoTalk_Photo_2023-11-27-14-01-14 002](https://github.com/NyangBotLab/Nyanyai/assets/107330816/ecae600e-46d9-4847-9ce6-e4d03f888e67)

**Comment by saroro1** [comment]
Very delighted :>>>>>>>>
